### ISSUE TITLE
where is quagmire

### ISSUE THREAD

**Issue by trudruchocolatemilk** [Naquino14/M-T-Bank-Spooktoberfestathon-and-Knuckles-feat.-Dante-From-Devil-May-Cry-Sponsored-By-M-T-Bank#2]
and also joe

we need brian bot

**Comment by Naquino14** [comment]
https://github.com/Naquino14/GiggityBot

**Comment by Naquino14** [comment]
https://github.com/Naquino14/WheelchairBot

**Comment by Naquino14** [comment]
https://github.com/Naquino14/DawgBot

**Comment by trudruchocolatemilk** [comment]
> 

hes dead and so is joe, make brian bot

**Comment by trudruchocolatemilk** [comment]
@Naquino14 dawg bot isnt real
![image](https://user-images.githubusercontent.com/43690740/197284936-6f033c18-f4c9-4f6c-8ab1-922ae1724516.png)

**Comment by Naquino14** [comment]
Private archive repo

**Comment by Naquino14** [comment]
Also your jordans are fake
